#!/bin/sh /etc/rc.common

USE_PROCD=1
# start before FreeRADIUS
START=49

start_service() {
  procd_open_instance
  procd_set_param command gunicorn -b 127.0.0.1:5000 "radguestauth.server:create_app()" -c python:radguestauth.server

  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

  procd_set_param file /etc/radguestauth/config.ini
  procd_set_param env RADGUESTAUTH_CONFIG=/etc/radguestauth/config.ini
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  procd_set_param user daemon
  procd_set_param term_timeout 15
  procd_set_param pidfile /var/run/radguestauth.pid
  procd_close_instance
}
